export const quickResponses: Record<string, string> = {
  "Tell me about Asbel": [
    "Asbel Nascimento is a motivated professional currently based in Dublin, Ireland.",
    "",
    "He has hands-on experience in quality inspection, customer service, and IT support, and is actively building technical skills in web development.",
    "",
    "He holds certifications from AWS, and has completed courses in front-end development, UX design, and programming fundamentals.",
    "",
    "He is a fast learner with a genuine curiosity for new technologies, and he has already built a professional portfolio website using React, TypeScript, and Express.",
    "",
    "Would you like to know more about his specific skills, experience, or certifications?",
  ].join("\n"),

  "What skills does he have": [
    "Asbel's key skills include:",
    "",
    "Technical:",
    "- HTML, CSS, JavaScript",
    "- Git & GitHub",
    "- Figma (UI/UX)",
    "- Microsoft Office",
    "- Hardware Troubleshooting",
    "- Networking Basics",
    "",
    "Professional:",
    "- Customer Service",
    "- Problem Solving",
    "- Time Management",
    "- Teamwork & Communication",
    "- Adaptability",
    "- Warehouse Operations",
    "",
    "He is also actively learning React, TypeScript, Node.js, and AWS cloud technologies.",
  ].join("\n"),

  "What certifications": [
    "Asbel holds 13 professional certifications:",
    "",
    "Cloud & AWS:",
    "1. AWS Cloud Foundations",
    "2. AWS - Foundations of Prompt Engineering",
    "3. Amazon Bedrock",
    "",
    "Development & Design:",
    "4. Introduction to Front-End Development",
    "5. UX Design: Digital Products",
    "6. Java - First Application",
    "7. Getting Started in Programming",
    "",
    "Tools & Professional:",
    "8. Git and GitHub Code Versioning",
    "9. Client x Server Communication",
    "10. Data Analysis - Google Sheets",
    "11. Masterclass Figma",
    "12. Career Transition to IT",
    "13. Administrative Assistant",
    "",
    "These demonstrate his commitment to continuous learning across multiple domains.",
  ].join("\n"),

  "Why should we hire him": [
    "Asbel brings a unique combination of real-world experience and a strong drive to learn. Here is why he stands out:",
    "",
    "- Diverse experience across quality inspection, customer service, and IT support",
    "- 13+ certifications earned while actively working shows dedication",
    "- Built a full-stack portfolio website with React, TypeScript, and Express",
    "- Already based in Dublin - no relocation or sponsorship needed",
    "- Reliable, punctual, and physically fit for demanding roles",
    "- Excellent teamwork and communication skills",
    "- Fast learner who genuinely enjoys acquiring new skills",
    "- Available immediately and ready to contribute",
    "",
    "He is the kind of person who takes initiative and grows with the team.",
  ].join("\n"),
};
